#!/bin/bash

function check_out()
{
	cd ~/CVS/Projects/$projectName/Project_Files
	if [ -f "$Name" ] 
	then	
		mv  ./$Name ~/CVS/Projects/$projectName/Working_Dir
		echo -e "\n File $Name moved to Working Directory of $projectName"
	fi
}

if [ $#=1 ] 
then
	projectName=$1
	#echo -e " Project $projectName"
	
	clear
	cd ~/CVS/Projects

	if [ -d $projectName ] 
	then
		cd ~/CVS/Projects/$projectName/Project_Files

		echo "<---------------------------------------------->"
		echo " 		     Check Out File "
		echo "<---------------------------------------------->"
		
		if [ ls = 0 ] 
		then	
			echo -e " There are no projects files "
		else	
			echo -e " Projects Files : "
			echo " " $(ls)
		fi # End if ls

		## DISPLAY WORD_DIR
		cd ~/CVS/Projects/$projectName/Working_Dir
	
		if [ ls = 0 ] 
		then	
			echo -e "\n There are no projects files \n"
		else	
			echo -e " \n Working Dir Files : "
			echo " " $(ls)
		fi # End if ls

		cd ~/CVS/Projects/$projectName/Project_Files

		echo -e "\n Enter File Name : "
	 	echo -en " "
		read Name

		if [ -f $Name ]	
		then	
			check_out
				
			echo -e "\n<---------------------------------------------->"
			echo " 	     File Check Out Complete "

			cd ~/CVS_install/scripts/Project_Scripts
			./edit_log "$projectName" "Checked Out $Name"
		else	
			echo -e "\n File does not exists in current directory. \n"
			echo "<---------------------------------------------->"
			echo " 	     File Check Out Aborted. "
		fi # end name
		echo -e "<---------------------------------------------->\n"
	else 
		echo -e "\n          $projectName does not exists. \n"
		echo -e "<---------------------------------------------->\n"
	fi
else 
echo -e " No valid project was supplied \n"
fi

exit 0
