#!/bin/bash

if [ $#=1 ]
then
	projectName=$1
	
else
	echo -e " No valid project was supplied \n"
fi

clear
cd ~/CVS/Projects/

if [ -d "$projectName" ]
then

	cd ~/CVS/Projects/$projectName/Project_Files

	if [ ls = 0 ] 
	then
		echo "<---------------------------------------------->"
		echo -e " There are no projects files \n"
	else
		echo "<---------------------------------------------->"
		echo -e " Projects Files : "
		echo " " $(ls)
	fi

	echo "<---------------------------------------------->"
	echo " 		     Remove Project "
	echo "<---------------------------------------------->"

	echo -e "\n Enter File Name : "
 	echo -en " "
	read Name

	if [ -f $Name ]
	then
	
		rm $Name
		echo -e " File $Name Deleted from $projectName \n"

		echo "<---------------------------------------------->"
		echo " 	     File Deletion Complete "

		cd ~/CVS_install/scripts/Project_Scripts
		./edit_log "$projectName" "Removed $Name"
	else
		echo -e "\n File does not exists. \n"
		echo "<---------------------------------------------->"
		echo " 	     File Deletion Aborted. "
	fi

	echo -e "<---------------------------------------------->\n"

else
	echo -e "\n          $projectName does not exists. \n"

	echo -e "<---------------------------------------------->\n"
fi

exit 0
