#!/bin/bash

trap ' ' 1 2 3 15 20

login_password="password"

echo ""
echo "<---------------------------------------------->"
echo " Login"
echo "<---------------------------------------------->"

echo ""
echo -n " Enter password "
echo -n " : "
read password
#password=password

while [ "$password" != "$login_password" ]
do
	echo "Password incorrect, Please try again!"
	echo -n " Password: "
	read password
done

echo -e "\n<---------------------------------------------->"
echo " Login Successful"
echo -e "<---------------------------------------------->\n"

chmod 777 menu

./menu
exit 0
