#!/bin/bash

# File Name:
# Author:
# Date Created:
# Date Last Modified:
# Purpose:
#Brief Description:

if [ $# = 2 ] 
then

	projectName=$1
	fileAccessed=$2
	
	projectDirectory=~/CVS/Projects/$projectName
	cd ~/CVS/Projects/
	
	if [ -d "$projectName" ] 
	then

		cd ~/CVS/Projects/$projectName/Logs

		set $(who am i)
		session=$4

		set $(date) 
		echo -e "Access Attempt - Time : $4 \n" >> ./Access_Log.txt
	
		echo "  User      - " $USER >> ./Access_Log.txt
		echo "  Session   - " $session >> ./Access_Log.txt
		echo "  Date      - " $1 $2 $3 >> ./Access_Log.txt
		echo -e "  Directory - " $projectDirectory >> ./Access_Log.txt
		echo -e "  File      - " $fileAccessed "\n" >> ./Access_Log.txt

		#gedit ./Access_Log.txt
	else
		echo -e "No directory \n"
	fi
else
		echo -e "No arguments \n"
fi

exit 0
