#!/bin/bash

if [ $# = 2 ] 
then
	projectName=$1
	subDir=$2
	#fileAccessed=$3
	
	cd ~/CVS/Projects/
	
	if [ -d "$projectName" ] 
	then

	cd ~/CVS/Projects/$projectName/Project_Files

	echo "<---------------------------------------------->"
	echo " 		    View Projects Files "
	echo "<---------------------------------------------->"

	cd ~/CVS/Projects/$projectName/Revisions
	if [ ls = 0 ]
	then
		echo -e "\n There are no projects files \n"
	else
		echo -e " \n Projects Files : "
	
		echo " " $(ls -1)
	fi

	echo -e "\n Enter File Name : "
	 	echo -en " "
		read Name

		if [ -f $Name ]	
		then

			returnFile=$Name
			#cd ~/CVS/Projects/$projectName/$subDir
			
			file="${Name%?????????????????????}"
			#echo $file".txt"
			Name=$file".txt"	
			
			# create new copy of file
		cp $returnFile ~/CVS/Projects/$projectName/Project_Files/"$Name"

			echo -e "\n $Name Restored sucessfully"

			#cd ~/CVS_install/scripts/Project_Scripts
			#./edit_log "$projectName" "Restored $Name Created"
		else
			echo -e "\n          $fileAccessed does not exists. \n"
			echo -e "<---------------------------------------------->\n"
		fi
	else 
		echo -e "\n          $projectName does not exists. \n"
		echo -e "<---------------------------------------------->\n"
	fi
else
		echo -e "No arguments \n"
fi

exit 0
